# This is a Server Config

[test]
name = "huangchao"
size = 18

# mysql config
[mysql]
dsn = ['127.0.0.1:123']


################################################################################
# redis

# 默认节点
[redis.default]
server = [
    "192.168.255.56:6371",
    "192.168.255.56:6372",
    "192.168.255.56:6373",
    "192.168.255.56:6374",
    "192.168.255.56:6375",
    "192.168.255.56:6376",
    "192.168.255.56:6377",
    "192.168.255.56:6378",
    "192.168.255.56:6379",
]

# redis connect timeout (ms)
[redis.default.connect]
timeout=1000

# redis write timeout (ms)
[redis.default.write]
timeout=500

# redis read timeout (ms)
[redis.default.read]
timeout=500

